import { readEnv } from '../env';

// Sends the one-time password to the student's phone. When no SMS provider is configured the app runs in demo mode
// (fixed OTP, no SMS) so it can still be shown without an account.
export interface SmsSender {
  sendOtp(input: { phone: string; otp: string }): Promise<void>;
}

export class SmsError extends Error {}

// MSG91 (https://msg91.com): the OTP is generated by us and passed to an approved DLT template that has an OTP variable.
const msg91: SmsSender = {
  async sendOtp({ phone, otp }) {
    const { msg91AuthKey, msg91TemplateId } = readEnv();
    const url = new URL('https://control.msg91.com/api/v5/otp');
    url.searchParams.set('template_id', msg91TemplateId);
    url.searchParams.set('mobile', `91${phone}`);
    url.searchParams.set('otp', otp);
    let res: Response;
    try {
      res = await fetch(url, { method: 'POST', headers: { authkey: msg91AuthKey, 'Content-Type': 'application/json' }, body: '{}', signal: AbortSignal.timeout(10_000) });
    } catch {
      throw new SmsError('SMS provider did not respond');
    }
    const out: any = await res.json().catch(() => null);
    if (!res.ok || out?.type !== 'success') throw new SmsError(`SMS provider rejected the request${out?.message ? `: ${out.message}` : ''}`);
  },
};

export const smsEnabled = (): boolean => {
  const e = readEnv();
  return e.smsProvider === 'msg91' && Boolean(e.msg91AuthKey && e.msg91TemplateId);
};

export const smsSender: SmsSender = msg91;
